name: Android P2P Hardcore Compiler

# Скрипт срабатывает автоматически при сохранении файлов или при ручном запуске кнопкой
on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем созданную вами структуру папок и кодов мессенджера
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      # 2. Разворачиваем стабильное окружение Java 17, необходимое для Gradle и Compose
      - name: Настройка Java 17 (Zulu JDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      # 3. Автоматически создаем исполняемый локальный Gradle Wrapper
      - name: Инициализация сборщика Gradle
        run: gradle wrapper --gradle-version 8.5

      # 4. Даем системе права на выполнение утилиты сборки пакетов
      - name: Rawanume 
        run: chmod +x gradlew

      # 5. Запуск компиляции защищенного

          
